### PR TITLE
Remove hard-coded library_id for intro detection

### PR DESCRIPTION
**Pull request by ArabCoders**
Removed hardcoded library_id in favor of get it all library_type =2 "tv type"

### CODE REVIEW

**Comment by animosity22** [comment]
Thanks for the fix!

**Comment by ArabCoders** [comment]
@animosity22 it seems plex has gotten smart and instead of populating the intros= entry, it parses the chapters and if it finds what look like Opening theme it uses it instead of analyzing the file.

**Comment by animosity22** [comment]
@ArabCoders  - Sorry to tag an old item but I was searching around and was wondering if you found anyway around this or anything else to look at? I've drawn blanks as I've checked the plexapi and that doesn't quite answer it.

**Comment by ArabCoders** [comment]
> @ArabCoders - Sorry to tag an old item but I was searching around and was wondering if you found anyway around this or anything else to look at? I've drawn blanks as I've checked the plexapi and that doesn't quite answer it.

@animosity22 Indeed i was able to pull the info using this sql

```sql
SELECT
    COUNT(0)
FROM
    media_parts mp
JOIN
    media_items mi
ON
    mi.id = mp.media_item_id
WHERE
    mi.library_section_id IN ( SELECT id FROM library_sections WHERE section_type = 2 )
AND
    mp.extra_data NOT LIKE '%intros=%'
AND
(
    SELECT 1 FROM taggings WHERE taggings.metadata_item_id = mi.metadata_item_id AND taggings.text = "intro" LIMIT 1
) IS NULL
```

**Comment by animosity22** [comment]
I'm trying to translate that back to the old settings that it produced:

```
19466 analyzed for intros
31113 not analyzed for intros
9199 have intros
```

That query you shared is giving me:

```
sqlite> SELECT
   ...>     COUNT(0)
   ...> FROM
   ...>     media_parts mp
   ...> JOIN
   ...>     media_items mi
   ...> ON
   ...>     mi.id = mp.media_item_id
   ...> WHERE
   ...>     mi.library_section_id IN ( SELECT id FROM library_sections WHERE section_type = 2 )
   ...> AND
   ...>     mp.extra_data NOT LIKE '%intros=%'
   ...> AND
   ...> (
   ...>     SELECT 1 FROM taggings WHERE taggings.metadata_item_id = mi.metadata_item_id AND taggings.text = "intro" LIMIT 1
   ...> ) IS NULL;
11658
```

Which is not analyzed items?

and something like this

```
sqlite> SELECT
   ...>     count(0)
   ...> FROM
   ...>     media_parts mp
   ...> JOIN
   ...>     media_items mi
   ...> ON
   ...>     mi.id = mp.media_item_id
   ...> WHERE
   ...>     mi.library_section_id IN ( SELECT id FROM library_sections WHERE section_type = 2 )
   ...> AND
   ...>     mp.extra_data LIKE '%intros=%'
   ...> AND
   ...> (
   ...>     SELECT 1 FROM taggings WHERE taggings.metadata_item_id = mi.metadata_item_id AND taggings.text = "intro" LIMIT 1
   ...> ) IS NULL;
10299
```
Gives me analyzed items? 

I just want to make sure I'm understanding that as I'm trying to produce the old results as I can see plex changed the intro a bit.

Some XML seems to have intro markers in the XML, while some just have Chapter markers which seem to do the same thing in terms of skipping.

**Comment by ArabCoders** [comment]
@animosity22 to get total of analyzed for intro files you would use this 
```sql
SELECT
                            count(0)
                        FROM
                            media_parts mp
                        JOIN
                            media_items mi
                        ON
                            mi.id = mp.media_item_id
                        WHERE
                            mi.library_section_id IN (
                                SELECT id FROM library_sections WHERE section_type = 2
                            )
                        AND
                        (
                            mp.extra_data LIKE \'%startTimeOffset%\'
                            OR
                            (
                                SELECT 1 FROM taggings WHERE taggings.metadata_item_id = mi.metadata_item_id AND taggings.text = "intro" LIMIT 1
                            ) IS NOT NULL
                        )
```

**Comment by animosity22** [comment]
Alright, thanks. I think I'm good on analyzed and not analyzed.

Is the have intros part still valid?

```
query="SELECT count(0) FROM media_parts mp JOIN media_items mi ON mi.id = mp.media_item_id WHERE mi.library_section_id IN ( SELECT id FROM library_sections WHERE section_type = 2 ) AND ( mp.extra_data LIKE '%startTimeOffset%' OR ( SELECT 1 FROM taggings WHERE taggings.metadata_item_id = mi.metadata_item_id AND taggings.text = 'intro' LIMIT 1 ) IS NOT NULL );"
result=$(sqlite3 -header -line "$db" "$query")
echo "${result:11} analyzed for intros"

query="SELECT COUNT(0) FROM media_parts mp JOIN media_items mi ON mi.id = mp.media_item_id WHERE mi.library_section_id IN ( SELECT id FROM library_sections WHERE section_type = 2 ) AND mp.extra_data NOT LIKE '%intros=%' AND ( SELECT 1 FROM taggings WHERE taggings.metadata_item_id = mi.metadata_item_id AND taggings.text = 'intro' LIMIT 1 ) IS NULL;"
result=$(sqlite3 -header -line "$db" "$query")
echo "${result:11} not analyzed for intros"

query="select count(*) from media_parts mp join media_items mi on mi.id = mp.media_item_id where mi.library_section_id IN (SELECT id FROM library_sections WHERE section_type = 2) and mp.extra_data like '%intros=%%7B%';"
result=$(sqlite3 -header -line "$db" "$query")
echo "${result:11} have intros"
```

**Comment by ArabCoders** [comment]
Ok i don't think it works like this anymore though, i used those 3 queries to determine the state of the videos.

```sql  
; total files analyzed.
SELECT
                            count(0)
                        FROM
                            media_parts mp
                        JOIN
                            media_items mi
                        ON
                            mi.id = mp.media_item_id
                        WHERE
                            mi.library_section_id IN (
                                SELECT id FROM library_sections WHERE section_type = 2
                            )
                        AND
                            mp.extra_data LIKE '%intros=%';

; has_skip_intro

SELECT
                            count(0)
                        FROM
                            media_parts mp
                        JOIN
                            media_items mi
                        ON
                            mi.id = mp.media_item_id
                        WHERE
                            mi.library_section_id IN (
                                SELECT id FROM library_sections WHERE section_type = 2
                            )
                        AND
                        (
                            mp.extra_data LIKE '%startTimeOffset%'
                            OR
                            (
                                SELECT 1 FROM taggings WHERE taggings.metadata_item_id = mi.metadata_item_id AND taggings.text = "intro" LIMIT 1
                            ) IS NOT NULL
                        );
; not_scanned

SELECT
                            COUNT(0)
                        FROM
                            media_parts mp
                        JOIN
                            media_items mi
                        ON
                            mi.id = mp.media_item_id
                        WHERE
                            mi.library_section_id IN (
                                SELECT id FROM library_sections WHERE section_type = 2
                            )
                        AND
                            mp.extra_data NOT LIKE '%intros=%'
                        AND
                        (
                            SELECT 1 FROM taggings WHERE taggings.metadata_item_id = mi.metadata_item_id AND taggings.text = "intro" LIMIT 1
                        ) IS NULL
```

**Comment by animosity22** [comment]
Ok, I'll just remove it as it's just not really needed.

I think my goal is just to make sure I can print out what media I need to analyze (short version, I made some changes so I need to validate intros which I created the issue)

I want my end output to be accurate so I'll remove any items that would confuse me or someone else.

I'll stick with just needing to analyze:

```
30.11.2021 13:36:39 PLEX LIBRARY STATS
Media items in Libraries
Library = MMA
  Items = 92

Library = Movies
  Items = 4669

Library = TV Shows
  Items = 50579

56430 files in library
0 files missing analyzation info
0 media_parts marked as deleted
0 metadata_items marked as deleted
0 directories marked as deleted
55340 files missing deep analyzation info.

11626 not analyzed for intros
```

and leave it as that.

I'm just doing this to print out my missing analysis and just selecting the seasons to reintro them as that does seem to be working.

```
#!/bin/bash

db="/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-in Support/Databases/com.plexapp.plugins.library.db"

query="SELECT file FROM media_parts mp JOIN media_items mi ON mi.id = mp.media_item_id WHERE mi.library_section_id IN ( SELECT id FROM library_sections WHERE section_type = 2 ) AND mp.extra_data NOT LIKE '%intros=%' AND ( SELECT 1 FROM taggings WHERE taggings.metadata_item_id = mi.metadata_item_id AND taggings.text = 'intro' LIMIT 1 ) IS NULL;"
result=$(sqlite3 -header -line "$db" "$query")
echo "${result:11} not analyzed for intros"

exit
```

Since Plex isn't picking them up automatically forwhatever reason.

**Comment by ArabCoders** [comment]
that should suffice indeed. xD

**Pull request merged**
